package com.mitenko.repkit.domain

import com.mitenko.repkit.domain.model.ProgressMode
import com.mitenko.repkit.domain.model.ProgressionConfig
import com.mitenko.repkit.domain.model.WeightConfig
import com.mitenko.repkit.domain.model.WeightSteps
import com.mitenko.repkit.domain.model.WeightsKind

/**
 * One problem with a weight config (spec rev 26 §3.1). Typed and free of English (plan Spec note 7):
 * PR 2 maps each to its field and a string. Indexes are list positions in [WeightConfig.list] or
 * [WeightConfig.holds].
 */
sealed interface WeightProblem {
    /** My weights: fewer than [WeightConfig.MIN_WEIGHTS]. */
    data object TooFewWeights : WeightProblem

    /** More than [WeightConfig.MAX_WEIGHTS], listed or generated by the steps. */
    data object TooManyWeights : WeightProblem

    /** My weights row [index] is ≤ 0 or over 999.75. */
    data class WeightOutOfRange(val index: Int) : WeightProblem

    /** My weights row [index] repeats an earlier row. */
    data class DuplicateWeight(val index: Int) : WeightProblem

    /** Steps: the start is ≤ 0 or over 999.75. */
    data object StepsStart : WeightProblem

    /** Steps: the step isn't one of [WeightValidator.STEP_CHOICES]. */
    data object StepsStep : WeightProblem

    /** Steps: the top is out of range, not above the start, or not reachable in whole steps. */
    data object StepsTop : WeightProblem

    data object RepsPerSet : WeightProblem

    data object RepMin : WeightProblem

    /** Out of 1..100, or not above the minimum. */
    data object RepMax : WeightProblem

    /** Not one of the current weights. */
    data object StartWeight : WeightProblem

    /** Outside the rep range. */
    data object StartReps : WeightProblem

    data object TooManyHolds : WeightProblem

    /** Hold [index]'s weight isn't on the ladder. */
    data class HoldWeight(val index: Int) : WeightProblem

    /** Hold [index]'s reps are outside the rep range. */
    data class HoldReps(val index: Int) : WeightProblem

    /** Hold [index]'s "for" is below 0. */
    data class HoldFor(val index: Int) : WeightProblem

    /** Hold [index] sits on the same position as an earlier hold (the later one carries it, as in rev 16 §3). */
    data class DuplicateHold(val index: Int) : WeightProblem
}

/**
 * Spec rev 26 §3.1, for every mode. Most rules don't depend on the mode, but the duplicate-hold rule
 * does (§10 note 10): in Weight mode two holds on one weight share a position, while in Reps then
 * weight they don't. So a switch to Weight can make a Reps-then-weight group with two holds on one
 * weight invalid; read-repair hides that by keeping the first hold on each position.
 */
object WeightValidator {
    /** The steps the Step stepper offers, in hundredths: 0.5, 1, 1.25, 2, 2.5, 5. */
    val STEP_CHOICES = listOf(50, 100, 125, 200, 250, 500)

    fun validate(c: WeightConfig, mode: ProgressMode): List<WeightProblem> = buildList {
        when (c.kind) {
            WeightsKind.LIST -> listProblems(c.list)
            WeightsKind.STEPS -> stepsProblems(c.steps)
        }
        if (c.repsPerSet !in 1..WeightConfig.MAX_REPS) add(WeightProblem.RepsPerSet)
        if (c.repMin !in 1..WeightConfig.MAX_REPS) add(WeightProblem.RepMin)
        if (c.repMax !in 1..WeightConfig.MAX_REPS || c.repMax <= c.repMin) add(WeightProblem.RepMax)
        val weights = c.weights.toSet()
        val range = c.repMin..c.repMax
        if (c.startWeight != null && c.startWeight !in weights) add(WeightProblem.StartWeight)
        if (c.startReps != null && c.startReps !in range) add(WeightProblem.StartReps)
        if (c.holds.size > ProgressionConfig.MAX_HOLDS) add(WeightProblem.TooManyHolds)
        val seen = HashSet<Pair<Int, Int>>()
        c.holds.forEachIndexed { i, h ->
            if (h.weight !in weights) add(WeightProblem.HoldWeight(i))
            if (h.reps !in range) add(WeightProblem.HoldReps(i))
            if (h.forCount < 0) add(WeightProblem.HoldFor(i))
            // Plan Spec note 10: a Weight-mode hold sits on its weight alone; otherwise on weight × reps.
            val position = if (mode == ProgressMode.WEIGHT) h.weight to 0 else h.weight to h.reps
            if (!seen.add(position)) add(WeightProblem.DuplicateHold(i))
        }
    }

    private fun MutableList<WeightProblem>.listProblems(list: List<Int>) {
        if (list.size < WeightConfig.MIN_WEIGHTS) add(WeightProblem.TooFewWeights)
        if (list.size > WeightConfig.MAX_WEIGHTS) add(WeightProblem.TooManyWeights)
        val seen = HashSet<Int>()
        list.forEachIndexed { i, w ->
            if (w !in 1..WeightConfig.MAX_WEIGHT) add(WeightProblem.WeightOutOfRange(i))
            else if (!seen.add(w)) add(WeightProblem.DuplicateWeight(i))
        }
    }

    private fun MutableList<WeightProblem>.stepsProblems(s: WeightSteps) {
        val startOk = s.start in 1..WeightConfig.MAX_WEIGHT
        val stepOk = s.step in STEP_CHOICES
        if (!startOk) add(WeightProblem.StepsStart)
        if (!stepOk) add(WeightProblem.StepsStep)
        val topOk = s.top in 1..WeightConfig.MAX_WEIGHT && s.top > s.start && (!stepOk || (s.top - s.start) % s.step == 0)
        if (!topOk) {
            add(WeightProblem.StepsTop)
        } else if (startOk && stepOk && (s.top - s.start) / s.step + 1 > WeightConfig.MAX_WEIGHTS) {
            add(WeightProblem.TooManyWeights)
        }
    }
}
